### PR TITLE
support for Patricia Gallardo

### PR DESCRIPTION
**Pull request by salimp2009**
You have my full support for this issue.
Support your and other community members requests on the changes.
We all want to safe place a to learn & share.

### CODE REVIEW

**Comment by patricia-gallardo** [comment]
There seems to be an issue with the branch in the PR maybe I can add your name manually?

**Comment by patricia-gallardo** [comment]
Or possibly you can make a new PR with a branch from master?

**Comment by salimp2009** [comment]
> There seems to be an issue with the branch in the PR maybe I can add your name manually?

which ever you like you can add it or I will try to make a new PR from master

**Comment by salimp2009** [comment]
> There seems to be an issue with the branch in the PR maybe I can add your name manually?
do i have to fork create a branch then do pull request ;  if this is the way i must, i will do it.
But you might as well add it manually

**Pull request closed without merging**
